draft , post like
Xuechunqiu/CMPUT404-project-socialdistribution pull request #106
Opened 2021-03-21 22:20 UTC by Weida-W

2021-03-21 23:42 UTC, Xuechunqiu commented on frontend/src/components/PostDisplay/index.js
> +      // );
You can delete these if no use.

2021-03-27 19:05 UTC, Xuechunqiu requested changes

2021-03-27 19:05 UTC, Xuechunqiu commented on backend/presentation/views.py
> +    print(like_list)
```suggestion
    print("-------")
    print(like_list)
```
Delete debugging codes

2021-03-27 19:05 UTC, Xuechunqiu commented on backend/presentation/views.py
> +    print(inbox.items)
```suggestion
    print(inbox.items)
```

2021-03-27 19:05 UTC, Xuechunqiu commented on backend/yarn.lock
> +
What's this?

2021-03-27 19:05 UTC, Xuechunqiu commented on backend/.inputrc
> +set completion-ignore-case on set show-all-if-ambiguous on TAB: menu-complete
What's this?

2021-03-27 19:05 UTC, Xuechunqiu commented on frontend/src/components/PostDisplay/index.js
> +    console.log("hhh: " + JSON.stringify(params));
```suggestion
    console.log("hhh: " + JSON.stringify(params));
```
same here

2021-03-27 19:05 UTC, Xuechunqiu commented on frontend/src/components/PostDisplay/index.js
> +          console.log("like");
```suggestion
          console.log("like");
```

2021-03-27 19:05 UTC, Xuechunqiu commented on frontend/src/components/PostDisplay/index.js
> +      console.log("params", params);
```suggestion
      console.log("params", params);
```

2021-03-28 04:06 UTC, Xuechunqiu approved these changes
Fix remaining things

2021-03-28 07:16 UTC, AcidCannon approved these changes
Good.

2021-03-28 07:19 UTC, AcidCannon commented
Should this merge into master branch?

2021-03-28 15:07 UTC, merged